Support CUBRID 9.3.9 on CentOS6
hgryoo/cubrid-vagrant-dev pull request #1
Opened 2019-06-26 06:57 UTC by wrlawodms

new line 관련된 이슈가 있습니다. 
diff를 보시면, 제가 건드렸다가 원복했던 파일들이 파일의 끝에 newline관련으로 다 변경된 것으로 보입니다. 
제가 찾아보기엔 linux, mac 컨벤션에 맞춰 vi가 자동으로 eol을 넣어줘서 그런듯합니다(set eol).
이를 제거할 수 있기는한데, 일반적으로 eol을 넣는것을 통용되는것 같아 일단 이상태로 풀리퀘 날립니다~ 의견주세요

2019-06-26 07:29 UTC, hgryoo requested changes

2019-06-26 07:29 UTC, hgryoo commented on cubrid10/centos6/post_install.sh
> +    cd ..
indent를 앞으로 빼놓은 이유가 있나요?

2019-06-26 07:29 UTC, hgryoo commented on cubrid10/centos6/post_install.sh
>  if [ ! -d myenv ]; then
이 부분은 빼는게 좋을 것 같네요.

2019-06-26 07:29 UTC, hgryoo commented on cubrid9/centos6/install_build.sh
> -yum install -y devtoolset-8-gcc* epel-release
cubrid9에 정확히 호환되는 gcc 버전을 설치하려면 devtoolset을 이용하는게 낫지 않을까요?

2019-06-27 01:19 UTC, wrlawodms commented on cubrid9/centos6/install_build.sh
> -yum install -y devtoolset-8-gcc* epel-release
9점대 버전에 정확히 호환되는 보전이 명확하지 않은듯합니다. 현재 관리되고 있지 않은듯 하고, 일단은 http://jira.cubrid.com:8888/browse/RND-704 에서 사용하는 버전이 4.4.7이니 이대로 가는게 어떨가 싶습니다.

2019-06-27 01:20 UTC, wrlawodms commented
new line 관련된 것은 그냥 이대로 진행할까요?

2019-06-27 06:52 UTC, wrlawodms commented on cubrid9/centos6/install_build.sh
> -yum install -y devtoolset-8-gcc* epel-release
버전 4.4.7로 명시하였습니다.

2019-06-27 07:04 UTC, merged

2019-06-27 07:04 UTC, hgryoo commented
merged